### ISSUE TITLE
'use strict' is required for my setup

### ISSUE THREAD

**Issue by GJSmith3rd** [GJSmith3rd/dns-over-http2#3]
It seems I have to use 

``` js
'strict mode';
```

DEBUG CONSOLE

node --debug-brk=15576 index.js 
Debugger listening on port 15576
/home/gjsmith3rd/Workspaces/GIT-Projects/dns-over-http2/index.js:28
    let question = req.question[0], hostname = question.name;
    ^^^
SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.runMain [as _onTimeout](module.js:442:10)
    at Timer.listOnTimeout (timers.js:92:15)

If I add 'strict mode' the code now runs but I'm confused about the parameters in dns-over-http2.json.

**Comment by Opensourcecommunitydevelopment** [comment]
yes i have added To My too As i saw it recently in your  https://github.com/GJSmith3rd/dns-over-http2/commit/528cffd9439506769bcbaea496a41240f8d9a7ce but forgot it in the pull request.. 

well if first line strict or Not i don't get this errors?and can't see difference with Node v6.8.0 Debugger listening on [::]:15576
for parameters @yyfrankyy would be better To ask about https://github.com/yyfrankyy/dns-over-http2

**Comment by GJSmith3rd** [comment]
Maybe because I'm on Node v4.2.6 - I'll look into upgrading.

**Comment by Opensourcecommunitydevelopment** [comment]
node --v8-Options
shows me:
  --use_strict (enforce strict mode)
        type: bool  default: false
