### ISSUE TITLE
What's are the arg parameters in dns-over-http2.json?

### ISSUE THREAD

**Issue by GJSmith3rd** [GJSmith3rd/dns-over-http2#4]
Is this the way it's set up? Do we need a forwarding DNS server or external IP?

``` js
{
  "apps" : [{
    "name"        : "dns-over-http2",
    "script"      : "~/Workspaces/GIT-Projects/dns-over-http2/index.js",
    "args"        : ["**external IP address** or **forwarding name servers**", 
                        port, 
                       "local dns-over-http2 server address"],
    "env": {
        "NODE_ENV": "production"
    }
  }]
}
```

**Comment by Opensourcecommunitydevelopment** [comment]
No the forwarding dns Server is currently hard coded To google public dns. No Need To set any.
No "External IP address“ Comes from the edns0 param, see: https://developers.google.com/speed/public-dns/docs/dns-over-https
but is optinaly and i did change it To be in End place so i can set in format
_localport_ _localip_ _externalipsubnet_
last is Not needed To be set. 
i  have set it up like this:
https://github.com/Opensourcecommunitydevelopment/dns-over-http2/blob/master/dns-over-http2.json

**Comment by GJSmith3rd** [comment]
OK, I removed my dns-over-http.json because it had my IP. Not a big deal. Hopefully, when we get synced back up and I brush up a bit more on pull request and branching I'll just use the one you have in the repo. 

I going to try a few more times tonight with the settings you have and check out some of the Google links you referenced tomorrow.

I'm running dnsmasq so I want to forward DNS request to dns-over-http2 but will just try to dig dns-over-http2 directly first.

Oh, that PM2 is pretty nice. Thanks for the tip.
